title: La médecine pour les oufs
baseurl: http://zharkov.github.io/la-medecine-pour-les-oufs/

markdown: redcarpet
redcarpet:
   extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "strikethrough", "autolink"]

pygments: true

permalink: title.html
